# Generated by Django 2.2.5 on 2019-09-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.FloatField(null=True)),
                ('name', models.CharField(max_length=20)),
                ('short_name', models.CharField(max_length=3)),
                ('team_division', models.IntegerField(null=True)),
            ],
        ),
    ]
