# Generated by Django 2.2.5 on 2019-09-03 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_division',
        ),
    ]
