# Generated by Django 2.2.5 on 2019-09-03 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_team_team_division'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='form',
        ),
    ]
