# Generated by Django 2.2.5 on 2019-09-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_team_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='draw',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='form',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='loss',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='played',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='points',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='position',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='strength',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='strength_attack_away',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='strength_attack_home',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='strength_defence_away',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='strength_defence_home',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='strength_overall_away',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='strength_overall_home',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='team_division',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='team_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='unavailable',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='win',
            field=models.IntegerField(null=True),
        ),
    ]
